# Generated by Django 3.2.9 on 2021-11-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='amount'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='category',
            field=models.CharField(max_length=50, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='image',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='price'),
        ),
    ]
