# Generated by Django 3.2.3 on 2021-11-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20211123_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.TextField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
